export const CREATE_GLOCERY_ITEM_SUCCESS = 'CREATE_GLOCERY_ITEM_SUCCESS';
export const LOAD_GLOCERY_ITEMS_SUCCESS = 'LOAD_GLOCERY_ITEMS_SUCCESS';
export const DELETE_GLOCERY_ITEM_SUCCESS = 'DELETE_GLOCERY_ITEM_SUCCESS';
export const TOGGLE_ITEM_PURCHASE_SUCCESS = 'TOGGLE_ITEM_PURCHASE_SUCCESS';
